In [ ]:
# 1. create a tensor
import torch
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.5126, 0.1656, 0.7351, 0.7165, 0.3404, 0.8859, 0.6712],
        [0.7020, 0.2489, 0.6061, 0.4248, 0.8085, 0.9156, 0.6777],
        [0.4985, 0.7223, 0.1592, 0.2122, 0.6081, 0.5516, 0.4949],
        [0.1839, 0.5942, 0.1165, 0.0390, 0.4320, 0.2667, 0.6886],
        [0.5408, 0.7126, 0.5075, 0.9810, 0.1396, 0.3061, 0.0933],
        [0.7353, 0.0658, 0.2394, 0.3629, 0.2059, 0.6023, 0.1235],
        [0.7904, 0.4439, 0.0139, 0.2200, 0.2606, 0.9927, 0.9972]])

In [ ]:
# 2. Matrix multiplication

random_tensor_2 = torch.rand(1, 7)
random_tensor_2

matmul = random_tensor * random_tensor_2.T
print(matmul)
print(matmul.shape)

tensor([[0.0102, 0.0033, 0.0147, 0.0143, 0.0068, 0.0177, 0.0134],
        [0.5457, 0.1934, 0.4712, 0.3302, 0.6285, 0.7117, 0.5268],
        [0.0954, 0.1383, 0.0305, 0.0406, 0.1164, 0.1056, 0.0947],
        [0.1255, 0.4055, 0.0795, 0.0266, 0.2948, 0.1820, 0.4700],
        [0.4567, 0.6019, 0.4286, 0.8285, 0.1179, 0.2585, 0.0788],
        [0.2575, 0.0230, 0.0838, 0.1271, 0.0721, 0.2109, 0.0432],
        [0.5598, 0.3144, 0.0098, 0.1558, 0.1846, 0.7031, 0.7063]])
torch.Size([7, 7])


In [ ]:
# random seed

seed = 0
torch.manual_seed(seed)

random_tensor = torch.rand(seed)
random_tensor

torch.manual_seed(seed)

random_tensor_2 = torch.rand(seed)
random_tensor_2

random_tensor == random_tensor_2

tensor([], dtype=torch.bool)

In [ ]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x, y, x.shape, y.shape)

z = torch.matmul(x, y.T)
z.shape

tensor([[0.0508, 0.2630, 0.8405],
        [0.4968, 0.2515, 0.1168]]) tensor([[0.0321, 0.0780, 0.3986],
        [0.7742, 0.7703, 0.0178]]) torch.Size([2, 3]) torch.Size([2, 3])


torch.Size([2, 2])

In [ ]:
random_tensor1 = torch.arange(1, 11)
random_tensor1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
z = torch.min(random_tensor1)

torch.Size([])

In [ ]:
random_tensor_3 = torch.rand(1, 1, 1, 10)
squeezed_tensor = torch.squeeze(random_tensor_3)
print(squeezed_tensor)


print(random_tensor_3, squeezed_tensor)
random_tensor_3 == squeezed_tensor

tensor([0.6581, 0.4897, 0.3875, 0.1918, 0.8458, 0.1278, 0.7048, 0.3319, 0.2588,
        0.5898])
tensor([[[[0.6581, 0.4897, 0.3875, 0.1918, 0.8458, 0.1278, 0.7048, 0.3319,
           0.2588, 0.5898]]]]) tensor([0.6581, 0.4897, 0.3875, 0.1918, 0.8458, 0.1278, 0.7048, 0.3319, 0.2588,
        0.5898])


tensor([[[[True, True, True, True, True, True, True, True, True, True]]]])